//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proga.БД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        public int id_заявка { get; set; }
        public string Дата_добавления { get; set; }
        public Nullable<int> Вид_оборудования { get; set; }
        public string Модель { get; set; }
        public string Описание_проблемы { get; set; }
        public Nullable<int> ФИО_клиента { get; set; }
        public string Телефон_клиента { get; set; }
        public Nullable<int> ФИО_мастера { get; set; }
        public Nullable<int> Статус_заявки { get; set; }
        public Nullable<int> Комментарий { get; set; }
        public string Дата_завершения { get; set; }
    
        public virtual Комментарий Комментарий1 { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Пользователь Пользователь1 { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
